#!/usr/bin/env bash
#print Holberton n-2 times.

number=1
while [ $number -le 10 ]; do
if [ $number -eq 4 ];
then
    echo "bad luck";
elif [ $number -eq 8 ];
then
    echo "good luck";
else
    echo "Holberton School"
fi;	
	number=$(( number + 1 ))
done
