#!/usr/bin/env bash
#print Holberton n-2 times.

number=1
while [ $number -le 20 ]; do
    echo "$number";
if [ $number -eq 4 ];
then
    echo "bad luck from China";
elif [ $number -eq 9 ];
then
    echo "bad luck from Japan";
elif [ $number -eq 17 ];
then
    echo "bad luck from Italy";
fi;	
	number=$(( number + 1 ))
done
